inherit_from: .rubocop_todo.yml
# 下記はチェック対象から除外する
AllCops:
  Exclude:
    - node_modules/**/*
    - vendor/**/*
    - db/schema.rb
    - tmp/**/*
    - bin/**/*
# アスキー以外のコメントを許可（日本語でのコメントが可能になる）
AsciiComments:
  Enabled: false
# クラスにコメントを残さないでも良い
Documentation:
  Enabled: false
# ABCMetricSizeのチェックの基準値を20にする
Metrics/AbcSize:
  Max: 20
